### ISSUE TITLE
build problems

### ISSUE THREAD

**Issue by galuel** [libre-money-projects/theorie-relative-de-la-monnaie#10]
When trying to generate RTM english from source code (which address is actually not in HTML index file that points towards french version), there was no total execution of  $ pip install -r /path/to/theorie-relative-de-la-monnaie/requirements.txt but it came to infinite run with the message : "Running setup.py install for numpy".

I Had to do so : 

```
$ pip install -vv numpy
```

and then instead of  $ pip install -r /path/to/theorie-relative-de-la-monnaie/requirements.txt I did : 

```
$ pip install -vv numpydoc
$ pip install -vv sphinx
$ pip install -vv ipython
$ pip install matplotlib
$ ./build_all.sh
```

Then I had the RTM generated ! ... in french version... (HTML, epub, pdf)

Then trying to continue to generate RTM english it stopped at the point "Add pot files index in .tx/config"

With message : 
## 

Error: Invalid value: Could not import 'txclib.utils'.
You need install transifex_client external library.
Please install below command if you want to this action:

```
$ pip install sphinx-intl[transifex]
```
## 

Then the command  $ pip install sphinx-intl[transifex] works , but still the same message when trying to continue. I stopped there.

Suggestions : 

Link to RTM english version source code in the "source code" link of the RTM english HTML index file, and not the french version.

Compiling the code refers to freedom 1 (access to source code and how to compile it to obtain the final software), and it's necessary to check all. Software freedom 2 refer to distribution of the software, and can be done by copying HTML, epub, pdf formats of the RTM english, so it should be good to have a zip file with HTML,epub,pdf formats of current RTM english version (development, or 0.1, or whatever) in the page : https://github.com/vtexier/theorie-relative-de-la-monnaie/releases so people who would like to distribute it for english language could do it even if they don't know or don't want to spend time to generate it from sources.

**Comment by vtexier** [comment]
I have fixed the README documentation.

Install with requirements.txt should work as expected, but with -vv, now we should see more information about compilation errors.

The Transifex part is reserved for the Transifex platform. It is here only for information, as it is no more used. The Transifex documentation has now its own chapter at the end.

There is a build_all_en_US.sh command to quickly build the english version. It is now added in the documentation.

Can you try it and tell me if it works for you ?
