### ISSUE TITLE
Extension error

### ISSUE THREAD

**Issue by moricef** [libre-money-projects/theorie-relative-de-la-monnaie#14]
Bonjour, 
J'ai téléchargé le projet et suivi le Readme pour installer les dépendances python sous Debian 8 3.16.0-4-amd64 et pour sourcer dans venv

Mais lorsque je lance un make latex dans le dossier du projet (donc sur le Makefile), j'ai cette erreur : 
```
make latex
sphinx-build -b latex -d build/doctrees -D latex_paper_size=a4  source build/latex
Running Sphinx v1.4.9
WARNING: sphinx.ext.pngmath has been deprecated. Please use sphinx.ext.imgmath instead.

Extension error:
sphinx.ext.pngmath: other math package is already loaded
Makefile:99: recipe for target 'latex' failed
make: *** [latex] Error 1
```
Je comprend donc qu'il y a une extension de trop de sphinx dans les supports des formules de math qui est lancée avant pngmath. Dans le conf.py, c'est sphinx.ext.mathjax (Render math via JavaScript). Je l'ai commenté puisque que  sphinx.ext.pngmath  suffit pour réussir la génération du document. Par ailleurs, pour corriger le warning concernant l'obsolescence de sphinx.ext.pngmath, j'ai remplacé celui-ci par sphinx.ext.imgmath (Render math as images).

Ceci dit je ne suis pas développeur et ne comprend pas grand-chose à python. Et ce que je cherche à faire, c'est générer la théorie-relative-de-la-monnaie en PDF au format A4 afin qu'il soit plus lisible et non pas pas au format livret comme ça l'est par défaut. Que me faut-il mettre comme options pour y parvenir? J'ai ajouter a4 dans le Makefile  mais sans succès :
```# You can set these variables from the command line.
SPHINXOPTS    =
SPHINXBUILD   = sphinx-build
PAPER         = a4
BUILDDIR      = build```

**Comment by vtexier** [comment]
Merci pour ce retour !

Pour le problème de l'extension, je pense que la version 1.4 de Sphinx casse des choses.
Il faudrait utiliser la même version que moi, à savoir la 1.3.1.

Pour cela, modifier le fichier requirements.txt : 

    sphinx==1.3.1

puis 

    pip install --upgrade -r requirements.txt
 
Pour info, ce qui installé chez moi via pip:
```
alabaster (0.7.6)
argparse (1.2.1)
Babel (2.0)
docutils (0.12)
ipython (2.3.1)
Jinja2 (2.8)
MarkupSafe (0.23)
matplotlib (1.4.2)
mock (1.0.1)
nose (1.3.4)
numpy (1.9.1)
numpydoc (0.5)
pip (1.5.6)
polib (1.0.5)
Pygments (2.0.2)
pyparsing (2.0.3)
python-dateutil (2.3)
pytz (2015.4)
setuptools (3.6)
six (1.9.0)
snowballstemmer (1.2.0)
Sphinx (1.3.1)
sphinx-intl (0.9.5)
sphinx-rtd-theme (0.1.8)
transifex-client (0.10)
wsgiref (0.1.2)
```

Sphinx est en python, mais requiert surtout de bien connaître sa documentation, qui est principalement de la configuration.

Ainsi, pour le format A4, la réponse semble être de mettre une option dans le fichier de config `source/conf.py` : 

```python
latex_elements = {
  # The paper size ('letterpaper' or 'a4paper').
  'papersize': 'a4paper',
```

**Comment by moricef** [comment]
Merci,
j'ai pu générer le pdf au format voulu avec vos indications et la doc de sphinx (et les forums, bien sûr) avec les paramètres latex suivants dans le `source/conf.py` : 


```
latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',
'papersize': 'a4paper',

# The font size ('10pt', '11pt' or '12pt').
'pointsize': '12pt',

'docclass':'report',

# Additional stuff for the LaTeX preamble.
'preamble': """
\usepackage{longtable,geometry}
\geometry{hmargin=2.5cm,vmargin=2.5cm}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[babel]{csquotes}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{tikz}
\usepackage{pgfplots}
\usepackage{empheq}
""",
}
```
