### ISSUE TITLE
Correction dans introduction à la version 2.718

### ISSUE THREAD

**Issue by jytou** [libre-money-projects/theorie-relative-de-la-monnaie#16]
Dans la version française, il y a une correction (validée avec Ğaluel) à faire dans le tout dernier paragraphe:
`Quelle règle ou quel principe peut-on poser pour que deux êtres imaginaires`
devrait être
`Quelle règle ou quel principe peut-on poser pour que *de* deux êtres imaginaires`
pour que ça colle avec la suite:
`l'un soit autorisé à maîtriser l'autre jusqu'à la consommation des siècles ?`

**Comment by morrme** [comment]
@vtexier @jytou i fixed this for you :smiley:

**Comment by vtexier** [comment]
@jytou , may be I wait for your future pull request before doing a new release.

**Comment by jytou** [comment]
Yes, I think it could be good. It will be quite a big pull request... :)
